import "./globals.css"
import type { Metadata } from "next"
import { Inter, Assistant } from "next/font/google"

const assistant = Assistant({ subsets: ["latin", "hebrew"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="he" dir="rtl">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </head>
      <body className={assistant.className}>{children}</body>
    </html>
  )
}
